# Generated by Django 5.1.3 on 2024-12-01 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hue_device_type', models.CharField(blank=True, max_length=100)),
                ('hub_id', models.IntegerField()),
                ('hue_id', models.CharField(max_length=100)),
                ('hue_id_v1', models.CharField(max_length=100)),
                ('model_id', models.CharField(max_length=100)),
                ('manufacturer_name', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('software_version', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('zigbee_rid', models.CharField(max_length=100)),
                ('power_rid', models.CharField(max_length=100)),
                ('last_checkin', models.DateTimeField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name': 'Hue Device',
            },
        ),
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=300)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hue.device')),
            ],
            options={
                'verbose_name': 'Hue Buttons',
            },
        ),
        migrations.CreateModel(
            name='Light',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid', models.CharField(max_length=100)),
                ('light_on', models.BooleanField(blank=True, null=True)),
                ('dimming', models.IntegerField(blank=True, null=True)),
                ('gamut_type', models.CharField(blank=True, max_length=50, null=True)),
                ('red', models.IntegerField(blank=True, null=True)),
                ('green', models.IntegerField(blank=True, null=True)),
                ('blue', models.IntegerField(blank=True, null=True)),
                ('effect', models.CharField(blank=True, max_length=50, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hue.device')),
            ],
            options={
                'verbose_name': 'Hue Light',
            },
        ),
    ]
