# Generated by Django 5.1.3 on 2024-12-01 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='bridge_rid',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='device',
            name='power_rid',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
