# Generated by Django 5.1.3 on 2024-12-04 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hue', '0002_device_bridge_rid_alter_device_power_rid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='light',
            name='dimming',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
