# Generated by Django 5.1.3 on 2024-12-18 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hue', '0003_alter_light_dimming'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='online',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
