# Generated by Django 5.1.3 on 2024-12-18 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hue', '0004_device_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='button',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hue.device', verbose_name='Device'),
        ),
        migrations.AlterField(
            model_name='button',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='button',
            name='rid',
            field=models.CharField(max_length=100, verbose_name='RID'),
        ),
        migrations.AlterField(
            model_name='device',
            name='bridge_rid',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bridge RID'),
        ),
        migrations.AlterField(
            model_name='device',
            name='hub_id',
            field=models.IntegerField(verbose_name='Hub ID'),
        ),
        migrations.AlterField(
            model_name='device',
            name='hue_device_type',
            field=models.CharField(blank=True, choices=[('WHITELAMP', 'White Lamp'), ('COLORLAMP', 'Color Lamp'), ('DIMSWITCH', 'Dimmer Switch'), ('HUB', 'Hue Hub')], max_length=100, verbose_name='Hue Device Type'),
        ),
        migrations.AlterField(
            model_name='device',
            name='hue_id',
            field=models.CharField(max_length=100, verbose_name='Hue ID'),
        ),
        migrations.AlterField(
            model_name='device',
            name='last_checkin',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Last Check-in'),
        ),
        migrations.AlterField(
            model_name='device',
            name='manufacturer_name',
            field=models.CharField(max_length=100, verbose_name='Manufacture Name'),
        ),
        migrations.AlterField(
            model_name='device',
            name='model_id',
            field=models.CharField(max_length=100, verbose_name='Model ID'),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='device',
            name='online',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Online'),
        ),
        migrations.AlterField(
            model_name='device',
            name='power_rid',
            field=models.CharField(blank=True, max_length=100, verbose_name='Power RID'),
        ),
        migrations.AlterField(
            model_name='device',
            name='product_name',
            field=models.CharField(max_length=100, verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='device',
            name='software_version',
            field=models.CharField(max_length=100, verbose_name='Software Version'),
        ),
        migrations.AlterField(
            model_name='device',
            name='zigbee_rid',
            field=models.CharField(max_length=100, verbose_name='ZigBee RID'),
        ),
        migrations.AlterField(
            model_name='light',
            name='blue',
            field=models.IntegerField(blank=True, null=True, verbose_name='Blue'),
        ),
        migrations.AlterField(
            model_name='light',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hue.device', verbose_name='Device'),
        ),
        migrations.AlterField(
            model_name='light',
            name='dimming',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Dimming'),
        ),
        migrations.AlterField(
            model_name='light',
            name='effect',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Effect'),
        ),
        migrations.AlterField(
            model_name='light',
            name='gamut_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Gamut Type'),
        ),
        migrations.AlterField(
            model_name='light',
            name='green',
            field=models.IntegerField(blank=True, null=True, verbose_name='Green'),
        ),
        migrations.AlterField(
            model_name='light',
            name='light_on',
            field=models.BooleanField(blank=True, null=True, verbose_name='Light On'),
        ),
        migrations.AlterField(
            model_name='light',
            name='red',
            field=models.IntegerField(blank=True, null=True, verbose_name='Red'),
        ),
        migrations.AlterField(
            model_name='light',
            name='rid',
            field=models.CharField(max_length=100, verbose_name='RID'),
        ),
    ]
