# Generated by Django 5.1.3 on 2025-01-01 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hue', '0005_alter_button_device_alter_button_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='battery_level',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
