# Generated by Django 5.1.3 on 2025-01-01 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hue', '0007_button_event_button_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='light',
            name='dimming',
            field=models.IntegerField(blank=True, null=True, verbose_name='Dimming'),
        ),
    ]
