# Generated by Django 5.1.3 on 2025-01-04 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hue', '0008_alter_light_dimming'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Button',
            new_name='HueButton',
        ),
        migrations.RenameModel(
            old_name='Device',
            new_name='HueDevice',
        ),
        migrations.RenameModel(
            old_name='Light',
            new_name='HueLight',
        ),
    ]
