# Generated by Django 5.1.3 on 2025-01-21 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hue', '0011_alter_huelight_switch'),
    ]

    operations = [
        migrations.AddField(
            model_name='huedevice',
            name='morph_sync',
            field=models.BooleanField(default=False, verbose_name='Sync to Devices'),
        ),
    ]
