# Generated by Django 5.1.3 on 2025-01-20 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scenes', '0004_scenedevices_switch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sort', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TileSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('sort', models.IntegerField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiles.page')),
                ('tile_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiles.tilesize')),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='page_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiles.pagetype'),
        ),
        migrations.CreateModel(
            name='TileType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tile_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiles.tilesize')),
            ],
        ),
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('tyle_type_id', models.IntegerField()),
                ('sort', models.IntegerField()),
                ('page_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiles.pagesection')),
                ('tile_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiles.tiletype')),
            ],
        ),
        migrations.CreateModel(
            name='SceneTile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('sort', models.IntegerField()),
                ('page_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiles.pagesection')),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenes.scene')),
                ('tile_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiles.tiletype')),
            ],
        ),
        migrations.CreateModel(
            name='NavTile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('sort', models.IntegerField()),
                ('page_nav', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiles.page')),
                ('page_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiles.pagesection')),
                ('tile_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiles.tiletype')),
            ],
        ),
    ]
