# Generated by Django 5.1.3 on 2025-01-21 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiles', '0003_remove_page_page_type_tile_sort_delete_pagetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='page_type',
            field=models.CharField(default='standard', max_length=100),
            preserve_default=False,
        ),
    ]
