# Generated by Django 5.1.3 on 2025-01-21 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiles', '0004_page_page_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tile',
            name='tile_object_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tile',
            name='tile_type',
            field=models.CharField(default='scene', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='page',
            name='page_type',
            field=models.CharField(choices=[('home', 'Home'), ('standard', 'Standard')], max_length=100),
        ),
    ]
