# Generated by Django 5.1.3 on 2025-01-06 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetype',
            name='display_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
