# Generated by Django 5.1.3 on 2025-01-06 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_devicetype_display_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devicetype',
            old_name='interface_name',
            new_name='interface_device_type',
        ),
    ]
