# Generated by Django 5.1.3 on 2025-01-10 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('devices', '0003_rename_interface_name_devicetype_interface_device_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Content Type'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_object_id',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Content Object ID'),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='capability',
            field=models.CharField(max_length=500, verbose_name='Capabilities'),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='display_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Display Name'),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='interface',
            field=models.CharField(max_length=100, verbose_name='Interface'),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='interface_device_type',
            field=models.CharField(max_length=100, verbose_name='Interface Display Name'),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
