# Generated by Django 5.1.3 on 2025-01-16 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_alter_device_device_content_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('favorite', models.BooleanField(verbose_name='Favorite')),
                ('hex_code', models.CharField(max_length=7, verbose_name='Hex Code')),
                ('red', models.IntegerField(verbose_name='Red')),
                ('green', models.IntegerField(verbose_name='Green')),
                ('blue', models.IntegerField(verbose_name='Blue')),
                ('color_family', models.ManyToManyField(to='devices.colorfamily', verbose_name='Color Family')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='devices.room', verbose_name='Room'),
        ),
    ]
