# Generated by Django 5.1.3 on 2025-01-17 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_colorfamily_room_color_device_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='sort',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sort'),
        ),
    ]
