# Generated by Django 5.1.3 on 2024-11-28 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('area', models.CharField(blank=True, max_length=100)),
                ('message', models.CharField(max_length=3000)),
                ('details', models.CharField(max_length=3000)),
                ('level', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'System Log',
            },
        ),
    ]
