# Generated by Django 5.1.3 on 2025-01-10 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0004_alter_device_device_content_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='SceneDevices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('light_on', models.BooleanField(blank=True, null=True, verbose_name='Light On')),
                ('dimming', models.IntegerField(blank=True, null=True, verbose_name='Dimming')),
                ('red', models.IntegerField(blank=True, null=True, verbose_name='Red')),
                ('green', models.IntegerField(blank=True, null=True, verbose_name='Green')),
                ('blue', models.IntegerField(blank=True, null=True, verbose_name='Blue')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.device', verbose_name='Device')),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenes.scene', verbose_name='Device')),
            ],
        ),
    ]
