# Generated by Django 5.1.3 on 2025-01-13 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenes', '0002_scenedevices_scene_device_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenedevices',
            name='scene_device_type',
        ),
        migrations.AddField(
            model_name='scenedevices',
            name='scene_device_capability',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Capabilities'),
        ),
    ]
