{'button': {'button_report': {'event': 'initial_press', 'updated': '2025-01-01T21:52:29.601Z'}, 'last_event': 'initial_press'}, 'id': '4b538982-d989-49aa-af75-4f75e1d97f72', 'id_v1': '/sensors/25', 'owner': {'rid': '3f13df38-5727-43c5-9219-a4f54fa77ad8', 'rtype': 'device'}, 'type': 'button'}


[
    {
        "capabilities":
        [
            "Actuator",
            "Refresh",
            "ColorTemperature",
            {
                "attributes":
                [
                    {
                        "name":"colorTemperature",
                        "currentValue":"4348",
                        "dataType":"NUMBER",
                        "values":null
                    },
                    {
                        "name":"colorName",
                        "currentValue":null,
                        "dataType":"STRING",
                        "values":null
                    }
                ]
            },
            "ColorMode",
            {
                "attributes":
                [
                    {
                        "name":"colorMode",
                        "currentValue":"CT",
                        "dataType":"ENUM",
                        "values":
                        [
                            "CT","RGB"
                        ]
                    }
                ]
            },
            "ColorControl",
            {
                "attributes":
                [
                    {
                        "name":"hue",
                        "currentValue":"60",
                        "dataType":"NUMBER",
                        "values":null
                    },
                    {
                        "name":"saturation",
                        "currentValue":"6",
                        "dataType":"NUMBER",
                        "values":null
                    },
                    {
                        "name":"color",
                        "currentValue":null,
                        "dataType":"STRING",
                        "values":null
                    },
                    {
                        "name":"colorName",
                        "currentValue":null,
                        "dataType":"STRING",
                        "values":null
                    },
                    {
                        "name":"RGB",
                        "currentValue":null,
                        "dataType":"STRING",
                        "values":null
                    }
                ]
            },
            "ChangeLevel",
            "SwitchLevel",
            {
                "attributes":
                [
                    {
                        "name":"level",
                        "currentValue":"100",
                        "dataType":"NUMBER","values":null
                    }
                ]
            },
            "Light",
            {
                "attributes":
                [
                    {
                        "name":"switch",
                        "currentValue":"off",
                        "dataType":"ENUM",
                        "values":
                        [
                            "on","off"
                        ]
                    }
                ]
            },
            "Switch",
            {
                "attributes":
                [
                    {
                        "name":"switch",
                        "currentValue":"off",
                        "dataType":"ENUM",
                        "values":
                        [
                            "on","off"
                        ]
                    }
                ]
            }
        ]
    }
]